# docker-compose.yaml
version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8200:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEOnW0lRBjeILazSsQnmu91/fP6vpehuOiQ3vWmiKaMH1VIH/f3cVFJFhOMQjRh7MLjNWNXy3n/ssvwYZdo+XV91orzcskkAcEv+LkXg5E4MRUP389RB2vuM3NGJKYMkoWSLVb8GuXbDGxpyp5yspelaJtebQZDJc2MEsK5Q2n+nwUvNvUNsrMHdw0SjLOlpFI/lzIz0JHfWKDkcoFxbSHme7aCSKCCxAjmiKqguTLgKHoxD6m9NUtNPqakHe8F9XEH6LQ/BlAu7I3S4qmigUMAPIJEYZkpsqKJ1sd7NLll0Fke3TPN6lYJg9VobgPJfUVShzHkCVonJuE3ZmvEG8aOvZLhQfO4s5ZypsUjAaTZAfDxm94MNAXQxVxmXNNI3o0dur4qvyORB+Aex7rggXoD4bWBhn8SIDP86LazbDt1fdSJH0FkKu1A8XVLDlelI+x/s7Ql0oYNv4ti5SAvLgXe1U2M5eYvCXyEoAIk6T3HmSARwe3n1Jwp/M7tazWLH0= opeter03@debian11-test
