---
- name: Pull nginx
  shell:
    cmd: "docker pull nginx"

- name: Create Volume
  shell:
    cmd: "docker volume create nginx-server-http"

- name: Create Volume
  shell:
    cmd: "docker volume create nginx-server-https"

- name: Run nginx http in docker container
  shell: |
    docker run --restart always --detach -p 8081:80 --name nginx-server-http -v nginx-server-http:/usr/share/nginx/html:ro -d nginx

- name: Run nginx https in docker container
  shell: |
    docker run --restart always --detach -p 8082:80 --name nginx-server-https -v nginx-server-https:/usr/share/nginx/html:ro -d nginx

- name: Create SSL directory
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Generate SSL
  become: yes
  shell: |
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx-testsec.key -out /etc/nginx/ssl/nginx-testsec.crt -subj "/C=HU/ST=PEST/O=IT"
    openssl dhparam -out /etc/nginx/dhparam.pem 4096

- name: Set NGINX virtualhosts
  become: yes
  shell: |
    echo '127.0.0.1 testbase.home' | sudo tee -a /etc/hosts
    echo '127.0.0.1 testsec.home' | sudo tee -a /etc/hosts

- name: HTML copy
  become: yes
  copy:
    src: htmls/http/index.html
    dest: /var/lib/docker/volumes/nginx-server-http/_data

- name: HTML copy
  become: yes
  copy:
    src: htmls/https/index.html
    dest: /var/lib/docker/volumes/nginx-server-https/_data

- name: SSL params copy
  become: yes
  copy:
    src: ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf

- name: Copy virtualhost template - http
  become: yes
  template:
    src: virtualhosts/testbase
    dest: /etc/nginx/sites-available/testbase
    owner: root
    group: root
    mode: '0644'
  vars:
    docker_port: 8081

- name: Copy virtualhost template - https
  become: yes
  template:
    src: virtualhosts/testsec
    dest: /etc/nginx/sites-available/testsec
    owner: root
    group: root
    mode: '0644'
  vars:
    docker_port: 8082

- name: Create symlink
  become: yes
  file: src=/etc/nginx/sites-available/testbase dest=/etc/nginx/sites-enabled/testbase state=link

- name: Create symlink
  become: yes
  file: src=/etc/nginx/sites-available/testsec dest=/etc/nginx/sites-enabled/testsec state=link

- name: restart nginx
  become: yes
  service: name=nginx state=restarted enabled=yes
