---
- name: Create working directory
  file:
    path: "{{ compose_dir }}"
    state: directory

- name: Clone a github repository
  git:
    repo: https://github.com/opeter03/udemx-laravel.git
    dest: "{{ compose_dir }}"
    clone: yes
    update: yes

- name: Copy .env
  copy:
    src: "{{ compose_dir }}/.env.example"
    dest: "{{ compose_dir }}/.env"

- name: .env file replace content
  shell: |
    awk -F= ' $1=="SESSION_DRIVER" {printf "%s=%s\n",$1,"file"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="DB_CONNECTION" {printf "%s=%s\n",$1,"mysql"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="# DB_HOST" {printf "DB_HOST=%s\n","db"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="# DB_PORT" {printf "DB_PORT=%s\n","3306"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="# DB_DATABASE" {printf "DB_DATABASE=%s\n","{{ laravel_db_db }}"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="# DB_USERNAME" {printf "DB_USERNAME=%s\n","{{ laravel_db_user }}"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env
    awk -F= ' $1=="# DB_PASSWORD" {printf "DB_PASSWORD=%s\n","{{ laravel_db_pw }}"; next}1' {{ compose_dir }}/.env > /tmp/.env && mv /tmp/.env {{ compose_dir }}/.env

- name: Create volume to DB
  shell:
    cmd: "docker volume create udemx-laravel-mysql-server-volume"

- name: Build container
  shell:
    cmd: "docker compose build app"
    chdir: "{{ compose_dir }}"

- name: Run container
  shell:
    cmd: "docker compose up -d"
    chdir: "{{ compose_dir }}"

- name: Run container commands
  shell:
    cmd: "docker compose exec app composer install && docker compose exec app php artisan key:generate && docker compose exec app php artisan migrate && docker compose exec app php artisan db:seed --class=CitiesSeeder"
    chdir: "{{ compose_dir }}"



