---
version: '3'

services:
    docker-registry:
        image: registry
        container_name: docker-registry
        ports:
            - 5000:5000
        restart: always
        volumes:
            - ./volume:/var/lib/registry
    docker-registry-ui:
        image: konradkleine/docker-registry-frontend:v2
        container_name: docker-registry-ui
        restart: always
        ports:
            - 8500:80
        environment:
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000
